apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-keycloak
  labels:
    app: polar-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polar-keycloak
  template:
    metadata:
      labels:
        app: polar-keycloak
    spec:
      containers:
        -   name: polar-keycloak
            image: quay.io/keycloak/keycloak:21.0.2-0
            args: ["start-dev --import-realm"]
            env:
              -   name: KEYCLOAK_ADMIN
                  value: user
              -   name: KEYCLOAK_ADMIN_PASSWORD
                  value: password
              -   name: KC_HTTP_PORT
                  value: '80'
              -   name: KC_HEALTH_ENABLED
                  value: 'true'
            ports:
              -   containerPort: 80
            volumeMounts:
              - mountPath: /opt/keycloak/data/import
                name: polar-keycloak
            readinessProbe:
              httpGet:
                path: /realms/master
                port: 80
      volumes:
        - name: polar-keycloak
          persistentVolumeClaim:
            claimName: polar-keycloak
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: polar-keycloak
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/docker/realm-config.json

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polar-keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: polar-keycloak
  labels:
    app: polar-keycloak
spec:
  type: ClusterIP
  selector:
    app: polar-keycloak
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
