apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-rabbitmq
  labels:
    message-broker: polar-rabbitmq
spec:
  selector:
    matchLabels:
      message-broker: polar-rabbitmq
  template:
    metadata:
      labels:
        message-broker: polar-rabbitmq
    spec:
      containers:
        - name: polar-rabbitmq
          image: rabbitmq:3.11.13-management
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 2000m
              memory: 1200Mi
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
      volumes:
        - name: rabbitmq-conf
          configMap:
            name: rabbitmq-conf

---

apiVersion: v1
kind: Service
metadata:
  name: polar-rabbitmq
  labels:
    message-broker: polar-rabbitmq
spec:
  type: ClusterIP
  selector:
    message-broker: polar-rabbitmq
  ports:
    - name: app-port  
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: manage-port
      protocol: TCP
      port: 15672
      targetPort: 15672

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-conf
  namespace: default
data:
  rabbitmq.conf: |
    default_user = user
    default_pass = password
