apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-postgres
  labels:
    db: order-postgres
spec:
  selector:
    matchLabels:
      db: order-postgres
  template:
    metadata:
      labels:
        db: order-postgres
    spec:
      containers:
        - name: order-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: order
            - name: POSTGRES_PASSWORD
              value: order
            - name: POSTGRES_DB
              value: polardb_order
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: order-postgres
  labels:
    db: order-postgres
spec:
  type: ClusterIP
  selector:
    db: order-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
