version: "3.8"
services:
  config-service:
    image: ghcr.io/ubaid4j/config-service:0.0.1-SNAPSHOT
    container_name: config-service
    ports:
      - "127.0.0.1:50100:50100"
  edge-service:
    depends_on:
      polar-keycloak:
        condition: service_healthy
    image: ghcr.io/ubaid4j/edge-service:0.0.2-SNAPSHOT
    container_name: edge-service
    ports:
      - "127.0.0.1:50090:50090"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:50100
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=1
      - SPRING_DATA_REDIS_HOST=polar-redis
      - SPRING_DATA_REDIS_PORT=6379
      - AUTH_SERVER_URL=http://polar-keycloak:50907
      - CATALOG_SERVICE_URL=http://catalog-service:50101
      - ORDER_SERVICE_URL=http://order-service:50201
      - SPA_URL=http://polar-ui:9004
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
      - polar-redis
      - polar-keycloak
    image: ghcr.io/ubaid4j/catalog-service:0.0.2-SNAPSHOT
    container_name: catalog-service
    ports:
      - "127.0.0.1:50101:50101"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_CLOUD_CONFIG_URI=http://config-service:50000
      - SPRING_PROFILES_ACTIVE=prod,testdata
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=50102
  order-service:
    depends_on:
      - polar-postgres
      - config-service
      - polar-keycloak
    image: ghcr.io/ubaid4j/order-service:0.0.1-SNAPSHOT
    container_name: order-service
    ports:
      - "127.0.0.1:50201:50201"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_CLOUD_CONFIG_URI=http://config-service:50000
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false
      - SPRING_PROFILES_ACTIVE=prod
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:50101
      - LOGGING_LEVEL_ROOT=debug
      - DEBUG=true
  dispatcher-service:
    image: ghcr.io/ubaid4j/dispatcher-service:0.0.1-SNAPSHOT
    container_name: dispatcher-service
    ports:
      - "127.0.0.1:50301:50301"
    environment:
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - polar-keycloak
  polar-postgres:
    image: postgres:latest
    container_name: polar-postgres
    ports:
      - "127.0.0.1:5590:5432"
    volumes:
      - ./postgres/init.sql/:/docker-entrypoint-initdb.d/init.sql
      - /private/storage/postgres-data/polar/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=polardb
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
  polar-redis:
    image: "redis:latest"
    container_name: "polar-redis"
    ports:
      - "127.0.0.1:50988:6379"
    volumes:
      - /private/storage/redis/polar-redis/:/data
  polar-rabbitmq:
    image: rabbitmq:3.11.13-management
    container_name: polar-rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  polar-keycloak:
    image: quay.io/keycloak/keycloak:21.0.2-0
    container_name: polar-keycloak
    command: start-dev --http-port 50907 --import-realm
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
      - ./keycloak/health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTP_PORT=50907
      - KC_HEALTH_ENABLED=true
    ports:
      - "127.0.0.1:50907:50907"
    healthcheck:
      test: "bash /opt/keycloak/health-check.sh"
      interval: 5s
      timeout: 10s
      retries: 12
  polar-ui:
    image: ghcr.io/ubaid4j/polar-ui:0.0.3-snapshot
    container_name: "polar-ui"
    ports:
      - "127.0.0.1:9004:9004"
    environment:
      - PORT=9004
