version: "3.8"
services:
  config-service:
    image: config-service:0.0.1-SNAPSHOT
    container_name: config-service
    ports:
      - "127.0.0.1:50000:50000"
  catalog-service:
    depends_on: 
      - polar-postgres
      - config-service
    image: catalog-service:0.0.1-SNAPSHOT
    container_name: catalog-service
    ports:
      - "127.0.0.1:50101:50101"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-postgres:5432/polardb_catalog
      - SPRING_CLOUD_CONFIG_URI=http://config-service:50000
      - SPRING_PROFILES_ACTIVE=prod,testdata
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=50102
  polar-postgres:
    image: postgres:latest
    container_name: polar-postgres
    ports:
      - "127.0.0.1:5590:5432"
    volumes:
      - ./postgres/init.sql/:/docker-entrypoint-initdb.d/init.sql
      - /private/storage/postgres-data/catalogservice/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=polardb
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust