version: "3.8"
services:
  config-service:
    image: config-service:0.0.1-SNAPSHOT
    container_name: config-service
    ports:
      - "127.0.0.1:50000:50000"
  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: catalog-service:0.0.1-SNAPSHOT
    container_name: catalog-service
    ports:
      - "127.0.0.1:50101:50101"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-postgres:5432/polardb_catalog
      - SPRING_CLOUD_CONFIG_URI=http://config-service:50000
      - SPRING_PROFILES_ACTIVE=prod,testdata
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=50102
  polar-postgres:
    image: postgres:latest
    container_name: polar-postgres
    ports:
      - "127.0.0.1:5590:5432"
    volumes:
      - ./postgres/init.sql/:/docker-entrypoint-initdb.d/init.sql
      - /private/storage/postgres-data/polar/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=polardb
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
  polar-redis:
    image: "redis:latest"
    container_name: "polar-redis"
    ports:
      - "127.0.0.1:50988:6379"
    volumes:
      - /private/storage/redis/polar-redis/:/data
  polar-rabbitmq:
    image: rabbitmq:3.11.13-management
    container_name: polar-rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  polar-keycloak:
    image: quay.io/keycloak/keycloak:21.0.2-0
    container_name: polar-keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "127.0.0.1:50907:8080"
  polar-ui:
    image: "ghcr.io/polarbookshop/polar-ui:v1"
    container_name: "polar-ui"
    ports:
      - "127.0.0.1:9004:9004"
    environment:
      - PORT=50090
