apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ubaid4j/order-service/k8s?ref=main
configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: order-service-config
replicas:
  - name: order-service
    count: 2
patches:
  - path: patch-evn.yml
  - path: patch-health.yaml

images:
  - name: ghcr.io/ubaid4j/order-service
    newName: ghcr.io/ubaid4j/order-service
    newTag: 0.0.6-snapshot