apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    spec:
      containers:
        - name: order-service
          livenessProbe:
            initialDelaySeconds: 150
            timeoutSeconds: 3
          readinessProbe:
            initialDelaySeconds: 120
            timeoutSeconds: 3