apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
spec:
  selector:
    matchLabels:
      app: edge-service
  template:
    spec:
      containers:
        - name: edge-service
          livenessProbe:
            initialDelaySeconds: 300
            timeoutSeconds: 3
          readinessProbe:
            initialDelaySeconds: 100
            timeoutSeconds: 3
          
      