apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    spec:
      containers:
        - name: dispatcher-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
    